### ISSUE TITLE
UnboundLocalError: local variable 'genoTypesPresent' referenced before assignment

### ISSUE THREAD

**Issue by qindan2008** [MathOnco/NeoPredPipe#1]
Hello,
I run NeoPredPipe using the data in the Example directory with the flowing command:

python main_netMHCpan_pipe.py -I ./Example/input_vcfs -H ./Example/HLAtypes/hlatypes.txt -o ./ -n TestRun -c 1 2 -E 8 9 10   

 But an error occurred:

INFO: Begin.
INFO: Proper directory already exists. Continue.
INFO: Proper directory already exists. Continue.
INFO: Proper directory already exists. Continue.
INFO: Proper directory already exists. Continue.
INFO: ANNOVAR Ready files for test1 already present.
INFO: ANNOVAR Annotation files for test1 already present.
INFO: Coding change fasta files for test1 already present.
INFO: Coding change fasta files test1 has already been reformatted.
INFO: Tmp fasta files test1 has already been created for netMHCpan length 8.
INFO: Tmp fasta files test1 has already been created for netMHCpan length 9.
INFO: Tmp fasta files test1 has already been created for netMHCpan length 10.
INFO: Epitope prediction files test1 have already been created for netMHCpan length 8.
INFO: Epitope prediction files test1 have already been created for netMHCpan length 9.
INFO: Epitope prediction files test1 have already been created for netMHCpan length 10.
INFO: Digesting neoantigens for test1
INFO: Digesting neoantigens for test1
INFO: Digesting neoantigens for test1
INFO: Object size of neoantigens: 72 Kb
Traceback (most recent call last):
  File "main_netMHCpan_pipe.py", line 438, in <module>
    main()
  File "main_netMHCpan_pipe.py", line 423, in main
    t.append(Sample(localpath, patname, patFile, hlas[patname], annPaths, netMHCpanPaths, pepmatchPaths, Options))
  File "main_netMHCpan_pipe.py", line 89, in __init__
    self.digestIndSample(pepmatchPaths, Options)
  File "main_netMHCpan_pipe.py", line 149, in digestIndSample
    self.appendedEpitopes, self.regionsPresent = AppendDigestedEps(self.digestedEpitopes, self.patID, self.annotationReady, self.avReadyFile, Options)
  File "/DataProcess/softwares/NeoPredPipe-master/postprocessing.py", line 138, in AppendDigestedEps
    return(newLines, genoTypesPresent)
UnboundLocalError: local variable 'genoTypesPresent' referenced before assignment

The pep fasta was downloaded from Ensembl, and pep index was build with the flowing command:
java -jar PeptideMatchCMD_1.0.jar -a index -d Homo_sapiens.GRCh37.75.pep.all.fa -i LuceneIndex

How can I fix it ?
Thank you.

**Comment by rschenck** [comment]
Just saw this. Will take a look into it.

**Comment by rschenck** [comment]
You are using a very outdated version of the scripts, line138 is not correct at all in the error you are reporting.

Can you please rerun with the latest version and let me know if you still have problems?
