### ISSUE TITLE
I don't get the results

### ISSUE THREAD

**Issue by kkyung412** [MathOnco/NeoPredPipe#15]
Hi I'm kyung
I am seting NeoPredPipe.

I made sure that all the preparation files were created.

but, There was no error in using the program, but there is nothing in the result file.
Please help me.

![image](https://user-images.githubusercontent.com/30678029/65604315-37022080-dfe2-11e9-9592-4f72dc07e621.png)

![image](https://user-images.githubusercontent.com/30678029/65604293-2b165e80-dfe2-11e9-9dcb-fc90550b9860.png)

**Comment by elakatos** [comment]
Hi Kyung,
It looks like there were no epitopes predicted at all for your input file. Usually this error occurs if something in netMHCpan is not set up properly (or if there are indeed no epitopes, but that has a very low chance I believe).
Can you run NeoPredPipe with the -d flag, so that the intermediate files and directories are preserved, and check what is inside your <samplename>.epitopes.X.txt files? In case the issue is with netMHCpan, you expect to see an error message, whilst otherwise it should look like the typical output of netMHCpan (http://www.cbs.dtu.dk/services/NetMHCpan/output.php, page bottom.)
Alternatively, can you run the included unit-test using "python neopredpipe_tests.py", which should throw an error if something is missing in the setup?

Please let me know how it goes,
Eszter

**Comment by kkyung412** [comment]
> Hi Kyung,
> It looks like there were no epitopes predicted at all for your input file. Usually this error occurs if something in netMHCpan is not set up properly (or if there are indeed no epitopes, but that has a very low chance I believe).
> Can you run NeoPredPipe with the -d flag, so that the intermediate files and directories are preserved, and check what is inside your .epitopes.X.txt files? In case the issue is with netMHCpan, you expect to see an error message, whilst otherwise it should look like the typical output of netMHCpan (http://www.cbs.dtu.dk/services/NetMHCpan/output.php, page bottom.)
> Alternatively, can you run the included unit-test using "python neopredpipe_tests.py", which should throw an error if something is missing in the setup?
> 
> Please let me know how it goes,
> Eszter


Hi Eszter,

I have an additional problem.
Can you guess why?

![image](https://user-images.githubusercontent.com/30678029/65608256-e6da8c80-dfe8-11e9-98db-2f217f46ebf3.png)

**Comment by kkyung412** [comment]
Hi Eszter,

I have an additional problem.
Can you guess why?

![image](https://user-images.githubusercontent.com/30678029/65608423-2608dd80-dfe9-11e9-81e6-d7d516c443b6.png)

**Comment by elakatos** [comment]
Hi,
Can you check that your netMHCpan file's path is provided correctly (and the whole path is provided) in your usr.ini?
Or it could be an issue with permissions regarding the netMHCpan file, make sure it is set to be executable by all (e.g. chmod 755 netMHCpan).

**Comment by kkyung412** [comment]
Of course. 

I checked all.

![image](https://user-images.githubusercontent.com/30678029/65609032-12aa4200-dfea-11e9-8996-3ad9f400d1ce.png)
![image](https://user-images.githubusercontent.com/30678029/65609084-28b80280-dfea-11e9-8914-e0ae4674bcde.png)

**Comment by elakatos** [comment]
I am a bit baffled by what could be the issue, as this did not happen on your previous run.
I would suggest either deleting the temporary files and restarting the analysis or trying to run the Example dataset - to see if/which error comes back.

**Comment by kkyung412** [comment]
Errors also occurred in the use of test codes. I really want to use this program.ᅲ
![image](https://user-images.githubusercontent.com/30678029/65610052-b8aa7c00-dfeb-11e9-94cb-fcb23ed6add6.png)

**Comment by elakatos** [comment]
Still seems to me something in your set-up might throw this error, as "/bin/sh" should not be found anywhere in NeoPredPipe's python files. However, I see on this run you used python3, which I cannot ensure works without errors, we developed the program in python2. I see that your previous run was on python2. I haven't tested NeoPredPipe with python3, so have no idea if it could cause a problem, but potentially swapping between python2 and python3 could lead to some unexpected errors.

The line where you seem to run into errors is before reaching NeoPredPipe, in trying to validate the fasta files that you aim to use. If with cleaning everything and restarting the analysis with consistent python version does not fix the issue, can you print out the variable "inFile" in line 27 of the file predict_binding.py ?
