### ISSUE TITLE
TypeII neoantigen detection errors

### ISSUE THREAD

**Issue by wangshun1121** [MathOnco/NeoPredPipe#19]
Hi:

I developed a perl script [NeoPredPipe.install.pl](https://github.com/wangshun1121/NeoPredPipe/blob/master/NeoPredPipe.install.pl) to deploy latest  NeoPredPipe, using following command:

```
perl NeoPredPipe.install.pl -i $PWD/NeoPredPipe -type2
```

There is a sample for typeII neoantigen calling in `$PWD/NeoPredPipe/Example/TypeII`, and I use following command to call neoantigen:

```
cd $PWD/NeoPredPipe
python NeoPredPipe.py -I ./Example/TypeII -H ./Example/TypeII/TypeII.txt -o ./Example/TypeIIout -n TestRun -c 1 2 -E 15
```

and error infos come:

```
INFO: Annovar reference files of build hg19 were given, using this build for all analysis.
INFO: Begin.
INFO: Running convert2annovar.py on ./Example/TypeII/TCGA-4B-A93V-01.vcf
INFO: ANNOVAR VCF Conversion Process complete ./Example/TypeII/TCGA-4B-A93V-01.vcf
INFO: Running annotate_variation.pl on ./Example/TypeIIout/avready/TCGA-4B-A93V-01.avinput
INFO: ANNOVAR annotation Process complete for ./Example/TypeIIout/avready/TCGA-4B-A93V-01.avinput
INFO: Running coding_change.pl on ./Example/TypeIIout/avannotated/TCGA-4B-A93V-01.avannotated.exonic_variant_function
INFO: Coding predictions complete for ./Example/TypeIIout/avannotated/TCGA-4B-A93V-01.avannotated.exonic_variant_function
INFO: Predicting neoantigens for TCGA-4B-A93V-01
INFO: Running Epitope Predictions for TCGA-4B-A93V-01 on epitopes of length 15.Indels
INFO: Running Epitope Predictions for TCGA-4B-A93V-01 on epitopes of length 15
INFO: Predictions complete for TCGA-4B-A93V-01 on epitopes of length 15
INFO: Digesting neoantigens for TCGA-4B-A93V-01
INFO: Object size of neoantigens: 77856 Kb
Traceback (most recent call last):
  File "NeoPredPipe.py", line 524, in <module>
    main()
  File "NeoPredPipe.py", line 505, in main
    t.append(Sample(localpath, patname, patFile, hlas[patname], annPaths, netMHCpanPaths, pepmatchPaths, Options))
  File "NeoPredPipe.py", line 108, in __init__
    self.digestIndSample(FilePath, pepmatchPaths, Options)
  File "NeoPredPipe.py", line 178, in digestIndSample
    self.appendedEpitopes, self.regionsPresent = AppendDigestedEps(FilePath, self.digestedEpitopes, self.patID, self.annotationReady, self.avReadyFile, Options)
  File "/shares/tools/NeoPredPipe/postprocessing.py", line 170, in AppendDigestedEps
    exonicLine = exonicInfo[epID]
KeyError: 1
```

it seems that `ANNOVAR` and `netMHCIIpan` can be processed properly, but there should be something wrong with  vcf format? 

By the way, using [NeoPredPipe.install.pl](https://github.com/wangshun1121/NeoPredPipe/blob/master/NeoPredPipe.install.pl) to deploy NeoPredPipe for TypeI pipeline, it works properly.

**Comment by wangshun1121** [comment]
I got the point! I use netMHCIIpan 4.0 instead of 3.x release. Output format has changed!
By the way, will NeoPredPipe be updated for adaptation of latest netMHCIIpan 4.0?

**Comment by elakatos** [comment]
Hi!
Thanks for letting me know, yes it was developed for the previous release of netMHCIIpan.
Should be fairly straightforward to change the output processing, so I'll look into adapting it in the coming weeks.
In the meantime, if you use the "no postprocessing" option (-pp), you can still use NeoPredPipe to at least arrive to the netMHCIIpan output files without throwing errors.
