### ISSUE TITLE
Issue about Running type-II HLA neoantigens

### ISSUE THREAD

**Issue by chenyx47** [MathOnco/NeoPredPipe#20]
Hello NeoPredPipe developers:

I am using the latest version of NeoPredPipe. I cloned the repo two days ago and saw that there are some updates about dectecting type-II HLA neoantigens. But I can't find any instruction for running such analysis in README. Could you provide me some advice.?

Any help would be greatly appreciated.
Thanks
Yancey

**Comment by elakatos** [comment]
Dear Yancey,

Support for MHC-II was not the primary function of this software, so I cannot guarantee that everything will run as smooth as with type-I predictions. But it is available, and I've just updated the Readme to include some instructions on how to run type-II predictions.
In a nutshell: we are currently supporting netMHCIIpan-3.2. If you supply the path to this in the "netMHCpan" section of the usr_paths.ini file, and set the epitope-length option appropriately (e.g. -E 15), the output should be automatically of type-II predicted peptides. If you use a different version of netMHCIIpan, the prediction files (tmp/*epitopes.txt) will still be produced, but no summary table and merged neoepitope table will be produced.

Best,
Eszter
