### ISSUE TITLE
python TabError problem

### ISSUE THREAD

**Issue by Xiaohuaniu0032** [MathOnco/NeoPredPipe#24]
Hi, i am testing the NeoPredPipe, and get the following problem:
```
$ python ./NeoPredPipe.py -h
Traceback (most recent call last):
  File "./NeoPredPipe.py", line 18, in <module>
    from vcf_manipulate import convert_to_annovar, annovar_annotation, get_coding_change,\
  File "/data1/workdir/fulongfei/git_repo/NeoPredPipe/vcf_manipulate.py", line 39
    vcf_file_chr = linespl[0]
                            ^
TabError: inconsistent use of tabs and spaces in indentation
```

I have fixed this problem, and here i open this issue just want to report this small bugs to you. thanks.

**Comment by elakatos** [comment]
Thank you for reporting this!
Just out of curiosity, can you let me know the specifics of your python version and environment (e.g. OS) when running into this?
