### ISSUE TITLE
BindLevel results from %Rank_EL or %Rank_BA

### ISSUE THREAD

**Issue by wt12318** [MathOnco/NeoPredPipe#29]
Hi,
The following is my output file:

![image](https://user-images.githubusercontent.com/39486023/112775615-f7e9db00-906f-11eb-9eb2-71cab3bbd795.png)

According to the [issue28](https://github.com/MathOnco/NeoPredPipe/issues/28), columns V21-V25 should be : Score_EL, %Rank_EL, Score_BA, %Rank_BA, Aff(nM).The `WB` BindLevel seems to be produced from `%Rank_EL`(>0.5 & <2); but I didn't set the `--EL` flag and this flag default is `false`. So from which column the  BindLevel results are produced ? `%Rank_EL` or `%Rank_BA`?

Thank you.

**Comment by elakatos** [comment]
Hi,
This is again I believe a difference between netMHCpan 4.0 and 4.1. I'd agree that the WB/SB tag is based on the %Rank of EL, as this is what they use by default in version 4.1. In this version the flag --BA (that we use by default in NeoPredPipe) only changes the output by adding the BA-related columns, but not what SB/WB is evaluated on (while in version 4.0 it meant WB/SB was based on BA rank). This should not be an issue for NeoPredPipe, as we directly use the WB/SB information from the software, and only require to have the Affinity value available for downstream processing in NeoRecoPo.

Eszter
