### ISSUE TITLE
vcf_manipulate.py

### ISSUE THREAD

**Issue by ChengYunazhi** [MathOnco/NeoPredPipe#3]
INFO: Annovar reference files of build hg19 were given, using this build for all analysis.
INFO: Begin.
INFO: Proper directory already exists. Continue.
INFO: Proper directory already exists. Continue.
INFO: Proper directory already exists. Continue.
INFO: Proper directory already exists. Continue.
INFO: ANNOVAR Ready files for XXX already present.
INFO: ANNOVAR Annotation files for XXXX already present.
INFO: Coding change fasta files for XXXX already present.
INFO: Coding change fasta files XXXX has already been reformatted.
Traceback (most recent call last):
  File "/DataProcess/softwares/NeoPredPipe-1.0/main_netMHCpan_pipe.py", line 456, in <module>
    main()
  File "/DataProcess/softwares/NeoPredPipe-1.0/main_netMHCpan_pipe.py", line 441, in main
    t.append(Sample(localpath, patname, patFile, hlas[patname], annPaths, netMHCpanPaths, pepmatchPaths, Options))
  File "/DataProcess/softwares/NeoPredPipe-1.0/main_netMHCpan_pipe.py", line 94, in __init__
    self.callNeoantigens(FilePath, netmhcpan, Options)
  File "/DataProcess/softwares/NeoPredPipe-1.0/main_netMHCpan_pipe.py", line 138, in callNeoantigens
    self.peptideFastas = MakeTempFastas(self.fastaChangeFormat, Options.epitopes)
  File "/DataProcess/softwares/NeoPredPipe-1.0/vcf_manipulate.py", line 138, in MakeTempFastas
    pos = int(seq_record.id.replace(";;",";").split(";")[6])-1
ValueError: invalid literal for int() with base 10: '493-494'

**Comment by rschenck** [comment]
Can you please verify that the example data works for you?

Further, can you please provide an example of the vcf you are using or the change Fasta file?

**Comment by ChengYunazhi** [comment]
example data works well. I found error was caused by "insertion" type in seq ID in fasta file, after change code in line 138, error was fixed. Thanks!

**Comment by rschenck** [comment]
Okay. Indels are currently not supported for the released version, but within the next couple of weeks we will be pushing a fix to include this. The problem for indels is the calculation of the Neoantigen recognition potentials. Currently NeoPredPipe should be filtering all indels.

**Comment by elakatos** [comment]
We have now updated the repository, and support for Indels (and any other frameshift type mutations) is included in the master branch. In the most recent version variants such as the above are considered for a separate XXX.neoantigens.Indels.txt and summary table. Let me know if there is still an issue with processing of the Annovar output.
