### ISSUE TITLE
BeoClass bug: in python 3 filter return an iterator.

### ISSUE THREAD

**Issue by tucano** [MathOnco/NeoPredPipe#39]
As for title, with python 3 filter return an iterator that you should cast to list.

With python 3:

`TypeError: 'filter' object is not subscriptable`. 

I have a pull request from this that check for filter features: https://github.com/MathOnco/NeoPredPipe/pull/40 :-)

**Comment by elakatos** [comment]
Thanks a lot for the fix! (I realised I never merged this fix from my local copy, but your fix is better!)
