### ISSUE TITLE
new error in postprocess

### ISSUE THREAD

**Issue by ChengYunazhi** [MathOnco/NeoPredPipe#4]
INFO: Annovar reference files of build hg19 were given, using this build for all analysis.
INFO: Begin.
INFO: Proper directory already exists. Continue.
INFO: Proper directory already exists. Continue.
INFO: Proper directory already exists. Continue.
INFO: Running convert2annovar.py on /DataProcess/standar_workflow/neoantigen/somatic_vcfs_varscan2_with_chr/WFGT.vcf
INFO: VCF Conversion Process complete /DataProcess/standar_workflow/neoantigen/somatic_vcfs_varscan2_with_chr/WFGT.vcf
INFO: ANNOVAR Annotation files for WFGT already present.
INFO: Coding change fasta files for WFGT already present.
INFO: Coding change fasta files WFGT has already been reformatted.
INFO: Predicting neoantigens for WFGT
INFO: Running Epitope Predictions for WFGT on epitopes of length 8
INFO: Running Epitope Predictions for WFGT on epitopes of length 9
INFO: Running Epitope Predictions for WFGT on epitopes of length 10
INFO: Predictions complete for WFGT on epitopes of length 10
INFO: Digesting neoantigens for WFGT
INFO: Digesting neoantigens for WFGT
INFO: Digesting neoantigens for WFGT
INFO: Object size of neoantigens: 824472 Kb
Traceback (most recent call last):
  File "/DataProcess/softwares/NeoPredPipe-1.0/main_netMHCpan_pipe.py", line 456, in <module>
    main()
  File "/DataProcess/softwares/NeoPredPipe-1.0/main_netMHCpan_pipe.py", line 441, in main
    t.append(Sample(localpath, patname, patFile, hlas[patname], annPaths, netMHCpanPaths, pepmatchPaths, Options))
  File "/DataProcess/softwares/NeoPredPipe-1.0/main_netMHCpan_pipe.py", line 96, in __init__
    self.digestIndSample(pepmatchPaths, Options)
  File "/DataProcess/softwares/NeoPredPipe-1.0/main_netMHCpan_pipe.py", line 156, in digestIndSample
    self.appendedEpitopes, self.regionsPresent = AppendDigestedEps(self.digestedEpitopes, self.patID, self.annotationReady, self.avReadyFile, Options)
  File "/DataProcess/softwares/NeoPredPipe-1.0/postprocessing.py", line 159, in AppendDigestedEps
    present = int(int(match.split(',')[1]) > 0) #present if depth for variant allele > 0
IndexError: list index out of range

**Comment by rschenck** [comment]
Please see other comment for the issue you have raised. We will look into this error.

**Comment by ChengYunazhi** [comment]
error was fixed. AD fields in varscan2 (somatic was called) is different, which cause split error. AD in varscan2 means variant allele depth, howere neoPredPipe supposed AD was "(Reference allele depth, Variant allele depth)". Thanks!

**Comment by rschenck** [comment]
Good to know. Will need to add more robustness for this
