### ISSUE TITLE
Is there any parameter to set up multithreading?

### ISSUE THREAD

**Issue by h170607** [MathOnco/NeoPredPipe#43]
hi
The prediction step takes a very long time. Can the running speed be increased by increasing the number of cores?

**Comment by elakatos** [comment]
Hi!
Unfortunately I believe that option is not available for netMHCpan 4.0 which performs the prediction.
I would advise running the whole pipeline in parallel for samples, e.g. if you have multiple samples to predict for, run a separate command for each sample (a straightforward way to set this up is to have one HLA file per sample).
