### ISSUE TITLE
AttributeError: 'Sample' object has no attribute 'appendedEpitopesIndels'

### ISSUE THREAD

**Issue by QianRongAn** [MathOnco/NeoPredPipe#45]
Run the example data, I receive this error:

python NeoPredPipe.py -I /mnt/bwa-0.7.17/wes/gatk4/gatk-4.0.6.0/0809_somatic.vcf -H /mnt/bwa-0.7.17/output/arcasHLA/arcasHLA/HLA/HRR572954.genotype.json -o ./ -n TestRun -c 1 2 -E 8 9 10
INFO: Annovar reference files of build hg38 were given, using this build for all analysis.
INFO: Begin.
INFO: Proper directory already exists. Continue.
INFO: Proper directory already exists. Continue.
INFO: Proper directory already exists. Continue.
INFO: Proper directory already exists. Continue.
Traceback (most recent call last):
  File "NeoPredPipe.py", line 524, in <module>
    main()
  File "NeoPredPipe.py", line 496, in main
    assert len(allFiles) > 0, "No input vcf files detected. Perhaps they are compressed?"
AssertionError: No input vcf files detected. Perhaps they are compressed?
(base) wangnan@fdfd046e92f0:/mnt/bwa-0.7.17/output/NeoPredPipe$ python NeoPredPipe.py -I ./Example/input_vcfs -H ./Example/HLAtypes/hlatypes.txt -o ./ -n TestRun -c 1 2 -E 8 9 10
INFO: Annovar reference files of build hg38 were given, using this build for all analysis.
INFO: Begin.
INFO: Proper directory already exists. Continue.
INFO: Proper directory already exists. Continue.
INFO: Proper directory already exists. Continue.
INFO: Proper directory already exists. Continue.
INFO: Running convert2annovar.py on ./Example/input_vcfs/test2.vcf
INFO: ANNOVAR VCF Conversion Process complete ./Example/input_vcfs/test2.vcf
INFO: Running annotate_variation.pl on ./avready/test2.avinput
INFO: ANNOVAR annotation Process complete for ./avready/test2.avinput
INFO: Coding change fasta files for test2 already present.
INFO: Coding change fasta files test2 has already been reformatted.
INFO: Tmp fasta files test2 has already been created for netMHCpan length 8.
INFO: Tmp fasta files test2 has already been created for netMHCpan length 9.
INFO: Tmp fasta files test2 has already been created for netMHCpan length 10.
INFO: Predicting neoantigens for test2
INFO: Skipping Sample! No peptides to predict for test2
INFO: Skipping Sample! No peptides to predict for test2
INFO: Skipping Sample! No peptides to predict for test2
INFO: Skipping Sample! No peptides to predict for test2
INFO: Skipping Sample! No peptides to predict for test2
INFO: Skipping Sample! No peptides to predict for test2
INFO: Predictions complete for test2 on epitopes of length 10.Indels
INFO: Running convert2annovar.py on ./Example/input_vcfs/test1.vcf
INFO: ANNOVAR VCF Conversion Process complete ./Example/input_vcfs/test1.vcf
INFO: Running annotate_variation.pl on ./avready/test1.avinput
INFO: ANNOVAR annotation Process complete for ./avready/test1.avinput
INFO: Coding change fasta files for test1 already present.
INFO: Coding change fasta files test1 has already been reformatted.
INFO: Tmp fasta files test1 has already been created for netMHCpan length 8.
INFO: Tmp fasta files test1 has already been created for netMHCpan length 9.
INFO: Tmp fasta files test1 has already been created for netMHCpan length 10.
INFO: Predicting neoantigens for test1
INFO: Skipping Sample! No peptides to predict for test1
INFO: Skipping Sample! No peptides to predict for test1
INFO: Skipping Sample! No peptides to predict for test1
INFO: Skipping Sample! No peptides to predict for test1
INFO: Skipping Sample! No peptides to predict for test1
INFO: Skipping Sample! No peptides to predict for test1
INFO: Predictions complete for test1 on epitopes of length 10.Indels
INFO: Summary Tables Complete.
Traceback (most recent call last):
  File "NeoPredPipe.py", line 524, in <module>
    main()
  File "NeoPredPipe.py", line 516, in main
    FinalOut(t, Options, True)
  File "NeoPredPipe.py", line 278, in FinalOut
    appendedEps = getattr(sampleClasses[i],epitopesToProcess)
AttributeError: 'Sample' object has no attribute 'appendedEpitopesIndels'

**Comment by elakatos** [comment]
Hi!
So if I understand correctly, you are running our example vcfs to test the pipeline. The examples files were created with reference hg19, but you are using hg38, so I think it can result in mis-translation of the variants and not leading to any protein-changing mutations and therefore no neoantigens. 
In terms of the first error you were getting before, you need to supply a folder where vcfs are located, so simply give the directory in which your vcf file is rather than the whole file path. And we haven't tested json outputs before, so I suggest to convert the output of arcasHLA to a txt file like the example one.

**Comment by evelyn-schmidt** [comment]
When running your exact command for using the testing data I get the same error and I seem to be using the correct reference.

```
python NeoPredPipe.py -I ./Example/input_vcfs -H ./Example/HLAtypes/hlatypes.txt -o ./ -n TestRun -c 1 2 -E 8 9 10
INFO: Annovar reference files of build hg19 were given, using this build for all analysis.
INFO: Begin.
INFO: Proper directory already exists. Continue.
INFO: Proper directory already exists. Continue.
INFO: Proper directory already exists. Continue.
INFO: Proper directory already exists. Continue.
INFO: ANNOVAR Ready files for test1 already present.
INFO: ANNOVAR Annotation files for test1 already present.
INFO: Coding change fasta files for test1 already present.
INFO: Coding change fasta files test1 has already been reformatted.
INFO: Tmp fasta files test1 has already been created for netMHCpan length 8.
INFO: Tmp fasta files test1 has already been created for netMHCpan length 9.
INFO: Tmp fasta files test1 has already been created for netMHCpan length 10.
INFO: Predicting neoantigens for test1
INFO: Skipping Sample! No peptides to predict for test1
INFO: Skipping Sample! No peptides to predict for test1
INFO: Skipping Sample! No peptides to predict for test1
INFO: Skipping Sample! No peptides to predict for test1
INFO: Skipping Sample! No peptides to predict for test1
INFO: Skipping Sample! No peptides to predict for test1
INFO: Predictions complete for test1 on epitopes of length 10.Indels
INFO: ANNOVAR Ready files for test2 already present.
INFO: ANNOVAR Annotation files for test2 already present.
INFO: Coding change fasta files for test2 already present.
INFO: Coding change fasta files test2 has already been reformatted.
INFO: Tmp fasta files test2 has already been created for netMHCpan length 8.
INFO: Tmp fasta files test2 has already been created for netMHCpan length 9.
INFO: Tmp fasta files test2 has already been created for netMHCpan length 10.
INFO: Predicting neoantigens for test2
INFO: Skipping Sample! No peptides to predict for test2
INFO: Skipping Sample! No peptides to predict for test2
INFO: Skipping Sample! No peptides to predict for test2
INFO: Skipping Sample! No peptides to predict for test2
INFO: Skipping Sample! No peptides to predict for test2
INFO: Skipping Sample! No peptides to predict for test2
INFO: Predictions complete for test2 on epitopes of length 10.Indels
INFO: Summary Tables Complete.
Traceback (most recent call last):
  File "NeoPredPipe.py", line 524, in <module>
    main()
  File "NeoPredPipe.py", line 516, in main
    FinalOut(t, Options, True)
  File "NeoPredPipe.py", line 278, in FinalOut
    appendedEps = getattr(sampleClasses[i],epitopesToProcess)
AttributeError: 'Sample' object has no attribute 'appendedEpitopesIndels'
```
