### ISSUE TITLE
RecognitionPotential: invalid literal for int() with base 10

### ISSUE THREAD

**Issue by tucano** [MathOnco/NeoPredPipe#48]
Hello! Hope you are well.

I found another small bug in NeoRecoPo.py using a reformatted neoantigens.Indels

Problem stacktrace:

```
INFO: Begin.
Traceback (most recent call last):
  File "/home/davide.rambaldi/src/NeoPredPipe/StandardPredsClass.py", line 260, in __extractSeq
    pos = int(seq_record.id.replace(";;", ";").split(";")[5]) - 1
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: '(position'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/davide.rambaldi/src/NeoPredPipe/NeoRecoPo.py", line 135, in <module>
    main()
  File "/home/davide.rambaldi/src/NeoPredPipe/NeoRecoPo.py", line 98, in main
    preds.ConstructWTFastas()
  File "/home/davide.rambaldi/src/NeoPredPipe/StandardPredsClass.py", line 195, in ConstructWTFastas
    self.__addToFastaFile()
  File "/home/davide.rambaldi/src/NeoPredPipe/StandardPredsClass.py", line 169, in __addToFastaFile
    seqID, seq = self.__extractSeq(sam, fasta_head, epitopeLength)  # WT seqID and seq
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/davide.rambaldi/src/NeoPredPipe/StandardPredsClass.py", line 262, in __extractSeq
    pos = int(seq_record.id.replace(";;", ";").split(";")[6]) - 1
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: '10-407'
```

This is due to this entry in fastaFiles `reformat.fasta`

```
>line3751;NM_000537;c.27delC;p.W10Gfs*37;protein-altering;;(position;10-407;changed;from;WGLLLLLWGSCTFGLPTDTTTFKRIFLKRMPSIRESLKERGVDMARLGPEWSQPMKRLTLGNTTSSVILTNYMDTQYYGEIGIGTPPQTFKVVFDT
MDGWRRMPRGDCCCCSGAPVPLVSRQTPPPLNGSSSRECPQSEKA*
```

In fact if I try this in console it fails:

```
a = 'line3751;NM_000537;c.27delC;p.W10Gfs*37;protein-altering;;(position;10-407;changed;from;WGLLLLLWGSCTFGLPTDTTTFKRIFLKRMPSIRESLKERGVDMARLGPEWSQPMKRLTLGNTTSSVILTNYMDTQYYGEIGIGTPPQTFKVVFDTGSSNVWVPSSKCSRLYTACVYHKLFDASDSSSYKHNGTELTLRYSTGTVSGFLSQDIITVGGITVTQMFGEVTEMPALPFMLAEFDGVVGMGFIEQAIGRVTPIFDNIISQGVLKEDVFSFYYNRDSENSQSLGGQIVLGGSDPQHYEGNFHYINLIKTGVWQIQMKGVSVGSSTLLCEDGCLALVDTGASYISGSTSSIEKLMEALGAKKRLFDYVVKCNEGPTLPDISFHLGGKEYTLTSADYVFQESYSSKKLCTLAIHAMDIPPPTGPTWALGATFIRKFYTEFDRRNNRIGFALAR*;to;GDCCCCSGAPVPLVSRQTPPPLNGSSSRECPQSEKA*)'

int(a.replace(";;",";").split(";")[6])

ValueError: invalid literal for int() with base 10: '10-407'
```

If you tell me which of the two integers I should use, I can propose a pull request with a small change in StandardPredsClass.py

Best Regards

Davide

**Comment by elakatos** [comment]
Hi Davide,
Thanks for the patience, not sure if it is still an issue, but I will look into it now.
The first integer is more relevant as the first position affected by the mutation. But theoretically, it should not matter which of the two numbers you use, as no wild-type peptide should be retro-predicted from indels - so I will double check why this processing step is even happening.
If by any chance you still have the corresponding files, did this mutation (line3751) as indel (i.e. ended up in the tmp.X.Indels.fasta file)?

**Comment by elakatos** [comment]
Hi Davide,
I double checked the code, and if you are processing indels, it does not seem to call the functions to ConstructWTFastas and extractSeq, so I did not manage to reproduce this error. Is it possible that you had this variant in not the "indel" neoantigen file? Or NeoRecoPo wasn't run with the --indel option?
I'll close the issue for now, but feel free to reopen if this error still exists with the --indel option.
