### ISSUE TITLE
get no neoantigen when running with Example .vcf files

### ISSUE THREAD

**Issue by Hupingdong** [MathOnco/NeoPredPipe#49]
Hi, 
I have run the NeoPredPipe.py as: 
`python NeoPredPipe.py -I ./Example/input_vcfs -H ./Example/HLAtypes/hlatypes.txt -o ./ -n TestRun -c 1 2 -E 8 9 10`
INFO: Annovar reference files of build hg19 were given, using this build for all analysis.
INFO: Begin.
INFO: Running convert2annovar.py on ./Example/input_vcfs/test1.vcf
INFO: VCF Conversion Process complete ./Example/input_vcfs/test1.vcf
INFO: Running annotate_variation.pl on ./avready/test1.avinput
INFO: ANNOVAR annotation Process complete for ./avready/test1.avinput
INFO: Running coding_change.pl on ./avannotated/test1.avannotated.exonic_variant_function
INFO: Coding predictions complete for ./avannotated/test1.avannotated.exonic_variant_function
INFO: Predicting neoantigens for test1
INFO: Running Epitope Predictions for test1 on epitopes of length 8
INFO: Skipping Sample! No peptides to predict for test1
INFO: Running Epitope Predictions for test1 on epitopes of length 9
INFO: Skipping Sample! No peptides to predict for test1
INFO: Running Epitope Predictions for test1 on epitopes of length 10
INFO: Skipping Sample! No peptides to predict for test1
INFO: Predictions complete for test1 on epitopes of length 10.Indels
INFO: Digesting neoantigens for test1
INFO: Digesting neoantigens for test1
INFO: Digesting neoantigens for test1
INFO: Object size of neoantigens: 56 Kb
INFO: Object size of neoantigens: 56 Kb
INFO: Running convert2annovar.py on ./Example/input_vcfs/test2.vcf
INFO: VCF Conversion Process complete ./Example/input_vcfs/test2.vcf
INFO: Running annotate_variation.pl on ./avready/test2.avinput
INFO: ANNOVAR annotation Process complete for ./avready/test2.avinput
INFO: Running coding_change.pl on ./avannotated/test2.avannotated.exonic_variant_function
INFO: Coding predictions complete for ./avannotated/test2.avannotated.exonic_variant_function
INFO: Predicting neoantigens for test2
INFO: Running Epitope Predictions for test2 on epitopes of length 8
INFO: Skipping Sample! No peptides to predict for test2
INFO: Running Epitope Predictions for test2 on epitopes of length 9
INFO: Skipping Sample! No peptides to predict for test2
INFO: Running Epitope Predictions for test2 on epitopes of length 10
INFO: Skipping Sample! No peptides to predict for test2
INFO: Predictions complete for test2 on epitopes of length 10.Indels
INFO: Digesting neoantigens for test2
INFO: Digesting neoantigens for test2
INFO: Digesting neoantigens for test2
INFO: Object size of neoantigens: 56 Kb
INFO: Object size of neoantigens: 56 Kb
INFO: Summary Tables Complete.
INFO: Summary Tables Complete.
INFO: Complete
and get the results with all 0. I use the netMHCpan-4.1 and python3. Is there something wrong with it?

**Comment by elakatos** [comment]
Hi,

Based on the "Object size of neoantigens: 56 Kb", I suspect this might be a similar error to this issue, i.e. something might be wrong with the netMHCpan set-up: https://github.com/MathOnco/NeoPredPipe/issues/38#issue-1907126770
Run the test again with keeping intermediate files/folders (-d flag), and check the direct netMHCpan output in the tmp folder.
